import baseRed from "material-ui/colors/red";
import baseOrange from "material-ui/colors/orange";
import baseLime from "material-ui/colors/yellow";
import baseGreen from "material-ui/colors/green";
import baseTeal from "material-ui/colors/teal";
import baseBlue from "material-ui/colors/blue";
import basePurple from "material-ui/colors/purple";
import baseGrey from "material-ui/colors/grey";

export const Red = baseRed.A700;
export const Orange = baseOrange.A700;
export const Lime = baseLime.A700;
export const Green = baseGreen.A700;
export const Teal = baseTeal.A700;
export const Purple = basePurple.A700;
export const Blue = baseBlue.A700;
export const Blue2 = "#0078D7";
export const White = baseGrey["50"];
// export const Black = basePurple["900"];
export const Black = "#21252b";
export const BlackBody = "#282c34";
export const GreyFont = "#ccccc1";
export const BlackPop = "#2f333d";
